### ISSUE TITLE
Full screen video

### ISSUE THREAD

**Issue by ignaciovaldes** [cocopon/vanillabox#10]
![captura de pantalla 2014-10-01 a las 10 05 26](https://cloud.githubusercontent.com/assets/6554443/4477242/8a196906-497c-11e4-836c-4d2d93a6d1d9.png)

**Comment by cocopon** [comment]
Sorry for the delay.
Does the problem still occur? Please tell me more information to reproduce the issue. It seems to work fine in my environment (OS X 10.10.1, Chrome latest, Firefox latest, etc.)
